name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: marian-code/python-lint-annotate@v4
        with:
          python-root-list: "worker/source/"
          use-black: true
          use-isort: true
          use-mypy: true
          use-pycodestyle: true
          use-pydocstyle: true
          extra-pycodestyle-options: "--max-line-length=88"
          use-pylint: true
          extra-pylint-options: "--fail-under=10"
          use-flake8: false
          use-vulture: true
          python-version: "3.11"
