name: Lint

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  checks: write

jobs:
  lint_python:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install black flake8

      # Run lint
      # Failure behavior
      # 1. When all steps above have completed successfully, begin lint execution
      # 2. When failure occurs, then indicate the failure in all associated PR checkers
      # 3. Do NOT halt lint execution (i.e. proceed if possible)
      # Note: In order to support failure behavior 3 above, the always() status function
      # appears below to avoid the default, which is success().
      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          black: true
          flake8: true
          continue_on_error: false
          neutral_check_on_warning: true
