name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          auto_fix: false
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: true
          neutral_check_on_warning: true

#      - uses: marian-code/python-lint-annotate@v4
#        with:
#          python-root-list: "worker/source/"
#          use-black: true
#          use-isort: true
#          use-mypy: true
#          use-pycodestyle: true
#          use-pydocstyle: true
#          extra-pycodestyle-options: "--max-line-length=88"
#          use-pylint: true
#          extra-pylint-options: "--fail-under=10"
#          use-flake8: false
#          use-vulture: true
#          extra-vulture-options: "--min-confidence 100"
#          python-version: "3.11"
