# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'worker/source/requirements.txt'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f worker/source/requirements.txt ]; then pip install -r worker/source/requirements.txt; fi
    - name: Run tests
      run: |
        pytest -vv --durations=0 -s -m unit
        pytest -vv --durations=0 -s -m integration
        pytest -vv --durations=0 -s -m system
