name: Static

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  checks: write

jobs:
  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      # Fetch the code and set up an interpreter
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Satisfy remaining requirements for static code analysis
      - name: Install dependencies
        run: pip install pylint black flake8

      # Failure behavior
      # 1. When all steps above have completed successfully, begin execution
      # 2. When failure occurs, then indicate it in the originating PR checker
      # 3. Do NOT stop static code analysis (i.e. proceed if possible)
      - name: Lint, code style, and formatting
        uses: wearerequired/lint-action@v2.3.0
        with:
          name: Foo
          pylint: true
          black: true
          flake8: true
          continue_on_error: false
          neutral_check_on_warning: true
