name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          auto_fix: false
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: true
          neutral_check_on_warning: true
  complete_regression:
    needs: lint
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r worker/source/requirements.txt
      - name: Run unit tests
        if: always()
        run: |
          cd worker/source/
          pytest -vv --durations=0 -s -m unit
      - name: Run integration tests
        if: always()
        run: |
          cd worker/source/
          pytest -vv --durations=0 -s -m integration
      - name: Run system tests
        if: always()
        run: |
          cd worker/source/
          pytest -vv --durations=0 -s -m system
