name: Complete regression test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r worker/source/requirements.txt
    - name: Run unit tests
      if: always()
      run: |
        cd worker/source/
        pytest -vv --durations=0 -s -m unit
    - name: Run integration tests
      if: always()
      run: |
        cd worker/source/
        pytest -vv --durations=0 -s -m integration
    - name: Run system tests
      if: always()
      run: |
        cd worker/source/
        pytest -vv --durations=0 -s -m system
