name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_full_regression:
    name: Full Regression Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r worker/source/requirements.txt
      - name: Prepare for testing
        id: prepare
        run: |
          cd worker/source/
      - name: Run unit tests
        run: |
          pytest -vv --durations=0 -s -m unit
      - name: Run integration tests
        if: always()
        run: |
          echo "Output [${{steps.prepare.outcome}}]"
          echo "Output [${{steps.prepare.output}}]"
          pytest -vv --durations=0 -s -m integration
      - name: Run system tests
        if: steps.prepare.outcome == 'success'
        run: |
          pytest -vv --durations=0 -s -m system
