name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_full_regression:
    name: Full Regression Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [ unit, integration, system ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r worker/source/requirements.txt
      - name: Run ${{ matrix.test-type }} tests
        if: always()
        run: |
          cd worker/source/
          pytest -vv --durations=0 -s -m ${{ matrix.test-type }}
